server:
  port: 8084
logging:
  level:
    root: info
spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            provider: gitee
            client-id: 0d5c6fadf9a31279c06b363e1d8da80aaf4b7e16db7c2447e4be9789d7a52bfa
            client-name: login_gitee
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8084/login/oauth2/code/gitee_login
            scope:
              - user_info
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
